print("Giraffe/nAcademy")

phrase = "Giraffe Academy"
print(phrase)
print(phrase + " is cool")
print(phrase.lower()) 
print(phrase.upper()) 
print(phrase.isupper()) 
print(phrase.upper().isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[3])
print(phrase.index("G")) 
print(phrase.index("Acad"))
print(phrase.replace("Giraffe", "Elephant"))
print(phrase.isdigit())
print(phrase.isalpha())
print(phrase.count("a"))
